### ISSUE TITLE
Resolve issue with NoseGAE and GAE 1.9.17 in pull request #170

### ISSUE THREAD

**Issue by brookisme** [wri/gfw-api#171]

**Comment by robinkraft** [comment]
Probably: `nose --with-gae --without-sandbox`

**Comment by brookisme** [comment]
Fixed in branch feature/issue169 [https://github.com/wri/gfw-api/pull/170]

commits:
https://github.com/wri/gfw-api/commit/96ab2f7f386d3a45387feae39dc1e99d4b0703e9
https://github.com/wri/gfw-api/commit/3e77554b5389fb5d68d263584f6a53bbdafb72e3
