### ISSUE TITLE
Replace "admin" in iso / ifl endpoints

### ISSUE THREAD

**Issue by brookisme** [wri/gfw-api#222]
* admin/:iso(/:id1) -> iso/:iso(/:id1)
* admin/ifl/:iso(/:id1) -> ifl/:iso(/:id1)

Note Vizzuality will need to make updates as well.  It might be worth having both endpoints for awhile and then completely removing admin at some future date

**Comment by brookisme** [comment]
* keep both admin(/ifl) and iso/ifl endpoints.
* in gfw/forestchange/api module ensure that _classify_request returns the correct (dataset,rtype) for iso and ifl

**Comment by eightysteele** [comment]
@brookisme @rashupee once this is ready i can send a PR to the vizz/gfw repo to land the api changes.

**Comment by brookisme** [comment]
Here's the PR https://github.com/wri/gfw-api/pull/230

**Comment by apercas** [comment]
Done. https://github.com/wri/gfw-api/pull/253
