### ISSUE TITLE
Urthecast MapTiles and Archive

### ISSUE THREAD

**Issue by brookisme** [wri/gfw-api#237]
Create a proxy for Urthecast [map-tiles](https://developers.urthecast.com/docs/map-tiles#examples) and [scenes](https://developers.urthecast.com/docs/archive).

- [x] create the proxy
- [ ] check that the response from urthecast is valid before sending map-tile
- [ ] ~~ensure only valid urls are passed to urthecast~~
- [x] cache results to improve performance
- [ ] write tests!

**Comment by eightysteele** [comment]
I say we skip checking valid URLs and valid responses. Let's just treat this as a straight through proxy (errors and all). Maybe?

Of course tests sound good. :)

**Comment by brookisme** [comment]
good plan - struck through the url validation for now

**Comment by rashupee** [comment]
Hi Aaron and Brookie,
I pushed up some exception handling for the map-tiles and archive/scenes urthecast proxies.
It's essentially based on urllib2's URLError and HTTPError. There's a confusion I am still having here that I'll ask Brookie about. But it catches errors and still forwards through appropriate data.
Also, the archive/scenes/<anything> seems to spit back scene info that is independent of what <anything> is...

**Comment by rashupee** [comment]
Hi Aaron and Brookie,
Memcache is working here for tiles. I added logging and exception handling - possibly too much exception handling. Urthecast times out a lot so I have a retry loop that tries a few times (with 5 second breaks) and logs the results before giving up. I'm going to create a pull request for that branch.
Hope y'all are well :)
